### ISSUE TITLE
4-relay should use the same interface as the 2-relay

### ISSUE THREAD

**Issue by toddkrein** [m5stack/M5Module-4Relay#2]
### Describe the bug

4-relay and 2-relay have essentially the same functionality, from a software perspective. They should use the same interface.

### To reproduce

Take the 2-relay module in UIFlow. Change the I2C address to 0x26. 
Take a CORE module, connect a 4-relay module to it.
Download the code, and run it.
See it fail.

### Expected behavior

It should just work.

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Module-4Relay/issues?q=)
- [X] My report contains all necessary details

**Comment by TinyuZhao** [comment]
Our documentation comes with circuit diagrams for both, 4relay for i2c control and 2relay for gpio control.
https://docs.m5stack.com/en/unit/4relay
https://docs.m5stack.com/en/unit/2relay
