### ISSUE TITLE
"4RELAY INIT ERROR" with Module_4RELAY_M5Core2.ino

### ISSUE THREAD

**Issue by sigmaeo** [m5stack/M5Module-4Relay#3]
### Describe the bug

Example didn't work because wrong I2C-Pins for I2C-PortA in Core2.
Core2 uses IO 32, 33 instead of 21, 22 for PORTA. 
21, 22 is internal I2C and 4Relay could not be connected to internal I2C as I know.

The line:
while (!RELAY.begin(&Wire**1**, MODULE_4RELAY_ADDR, **21, 22**, 200000L)) {

Should be changed to:
while (!RELAY.begin(&Wire, MODULE_4RELAY_ADDR, 32, 33, 200000L)) {

### To reproduce

- Arduino IDE 2.2.1
- M5StackCore2 0.1.6 or 0.1.7
- Hardware: Core2 and 4-Relay UNit connected to PORTA.
- Compile the example sketch "Module_4RELAY_M5Core2.ino"

### Expected behavior

Core2 should initalize and relay should make sound.

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Module-4Relay/issues?q=)
- [X] My report contains all necessary details

**Comment by sigmaeo** [comment]
Sorry I tried with "Unit 4Relay" and not with "Module 4Relay".
I missed the fact, that there are two hardwares and two repos/libs.

**Comment by imliubo** [comment]
Hi @sigmaeo ,

Yes, module and unit is different, the I2C interface module normally use the **intSDA** and **intSCL** pin, but if you connect the I2C interface UNIT to PortA, it use **PA_SDA** and **PA_SCL** in Core2/CoreS3 device.

So, i will close this issues, feel free to reopen this if you still have issues.
